name:  Apiit Golden Path 

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: Enchanter1015/golden-path-catalog/.github/workflows/react.deploy.yaml@v3.0.1
    with:
      team:        Development
      environment: prod
      project:     apiit-saas
      catalog_ver: v3.0.1
      aws_region:  us-east-1
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}